CREATE TABLE NOTIFICATION (
    IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
    TEXT varchar(255),
    CATEGORY varchar(255),
    PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE PROFILE (
    IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
    DIABETIC BOOLEAN NOT NULL,
    DYSLIPIDEMIC BOOLEAN NOT NULL,
    FAMILY_ANTECEDENT BOOLEAN NOT NULL,
    GENDER VARCHAR(255),
    HEIGHT INTEGER NOT NULL,
    HYPERTENSIVE BOOLEAN NOT NULL,
    MARRIED BOOLEAN NOT NULL,
    MENOPAUSE BOOLEAN NOT NULL,
    PERSONAL_ANTECEDENT BOOLEAN NOT NULL,
    SMOKER BOOLEAN NOT NULL,
    WEIGHT INTEGER NOT NULL,
    PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE USER (
    IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
    AGE INTEGER NOT NULL,
    EMAIL VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PROFILE_ID BIGINT,
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE USER ADD CONSTRAINT FKOF44U64O1D7SCAUKGHM9VEO23 FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE